version: "1"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - noctx
    - predeclared
    - revive
    - unconvert
    - wastedassign

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
